data-ingestion:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres-data
      user: data_user
      password: data_pass
      port: 5432
      dbname: data_ingestion
      schema: public
      threads: 1
      keepalives_idle: 0
      connect_timeout: 10
      retries: 2